CREATE OR REPLACE TABLE "DATALAKE_DEMO"."MATILLION"."STG_VIDEOSTART" 
(	
    "DATETIME" datetime NOT NULL, 
    "PLATFORM" VARCHAR2(200) NOT NULL, 
    "SITE" VARCHAR2(200) NOT NULL, 
    "VIDEO" VARCHAR2(200) NOT NULL
);